### PR TITLE
Add rambling.malignat.us

### PR DESCRIPTION
**Pull request by MordecaiMalignatus**
After being *kindly encouraged* to do so, I edited my original blog to be just this, since I can definitely use the opportunity for reflection and thinking. 

Might want to wait a bit for DNS/HTTPS to catch up, unsure how GH pages works here exactly.

### CODE REVIEW

**Comment by rixx** [comment]
It just runs as a cronjob on some server to rebuild the aggregated feed, so DNS should be fine. Welcome on the list!

**Comment by MordecaiMalignatus** [comment]
Hold on, let me add contact data and such, forgot about that

**Comment by MordecaiMalignatus** [comment]
Just a second too slow :D

**Comment by rixx** [comment]
Gave you access, you can just edit it yourself :P

**Comment by MordecaiMalignatus** [comment]
That does indeed work, too :D. I was just going to leave it, contact
stuff's on the blog.

**Pull request merged**
